const sql       = require('mssql');
const path      = require('path');
const config    = require(path.join(process.cwd(), 'config'));

async function connectDB() {
    await sql.connect(`mssql://${config.DB.USER}:${config.DB.PASSWORD}@${config.DB.SEVER}/${config.DB.REPORTS_DB}?encrypt=true`);
}

// Save point generated by lib
async function saveGeneratedPoints(points, calc_time) {
    var point = points[0];
    await connectDB();
    var insertQuery = `INSERT INTO ${config.DB.REPORTS_DB} (`;
    // insertQuery += "id,"; Automatically incremented from the CREATE TABLE... id uniqueidentifier default NEWSEQUENTIALID() primary key command
    insertQuery += "datetime,";
    insertQuery += "visited,";
    insertQuery += "gid,";
    insertQuery += "tid,";
    insertQuery += "lid,";
    insertQuery += "type,";
    insertQuery += "x,";
    insertQuery += "y,";
    insertQuery += "latitude,";
    insertQuery += "longitude,";
    insertQuery += "distance,";
    insertQuery += "initial_bearing,";
    insertQuery += "final_bearing,";
    insertQuery += "side,";
    insertQuery += "distance_err,";
    insertQuery += "radiusM,";
    insertQuery += "number_points,";
    insertQuery += "mean,";
    insertQuery += "rarity,";
    insertQuery += "power_old,";
    insertQuery += "power,";
    insertQuery += "z_score,";
    insertQuery += "probability_single,";
    insertQuery += "integral_score,";
    insertQuery += "significance,";
    insertQuery += "probability";
    insertQuery += ") VALUES (";
    insertQuery += `'${calc_time}',`; // datetime
    insertQuery += `'0',`; // visited
    insertQuery += `'${point.GID}',`; // gid
    insertQuery += `'${point.TID}',`; // tid
    insertQuery += `'${point.LID}',`; // lid
    insertQuery += `'${point.type}',`; // type
    insertQuery += `'${point.x}',`; // x
    insertQuery += `'${point.y}',`; // y
    insertQuery += `'${point.latitude}',`; // latitude
    insertQuery += `'${point.longitude}',`; // longitude
    insertQuery += `'${point.distance}',`; // distance
    insertQuery += `'${point.initialBearing}',`; // initial_bearing
    insertQuery += `'${point.finalBearing}',`; // final_bearing
    insertQuery += `'${point.side}',`; // side
    insertQuery += `'${point.distanceErr}',`; // distance_err
    insertQuery += `'${point.radiusM}',`; // radiusM
    insertQuery += `'${point.n}',`; // number_points
    insertQuery += `'${point.mean}',`; // mean
    insertQuery += `'${point.rarity}',`; // rarity
    insertQuery += `'${point.power_old}',`; // power_old
    insertQuery += `'${point.power}',`; // power
    insertQuery += `'${point.z_score}',`; // z_score
    insertQuery += `'${point.probability_single}',`; // probability_single
    insertQuery += `'${point.integral_score}',`; // integral_score
    insertQuery += `'${point.significance}',`; // significance
    insertQuery += `'${point.probability}'`; // probability"
    insertQuery += ");"
    console.log(`INSERT query: ${insertQuery}`)
    const result = await sql.query(insertQuery);
    console.dir(result)
}

// Update lib-generated record with details of trip report
async function saveTripReport(req, res, next) {
    var report = req.body;
    await connectDB();
    var updateQuery = `UPDATE ${config.DB.REPORTS_DB} SET `;
    updateQuery += `user_id = ${report.point_id},`;
    updateQuery += `platform = ${report.platform},`;
    updateQuery += `point_type = ${report.point_type},`;
    updateQuery += `intent_set = ${report.intent_set},`;
    updateQuery += `artifact_collected = ${report.artifact_collected},`;
    updateQuery += `fucking_amazing = ${report.fucking_amazing},`;
    updateQuery += `rating_meaningfulness = ${report.rating_meaningfulness},`;
    updateQuery += `rating_emotional = ${report.rating_importance},`;
    updateQuery += `rating_importance = ${report.rating_importance},`;
    updateQuery += `rating_strangeness = ${report.rating_strangeness},`;
    updateQuery += `rating_synchroncity = ${report.rating_synchroncity},`;
    // TODO: Upload photos to imgur etc, and save comma separated URLs in this field
    // updateQuery += `photos = '${photoUrls}',";
    updateQuery += `text = ${report.text},`;
    if (userProfileTemporary.IntentSuggestions != null && userProfileTemporary.IntentSuggestions.Length > 0)
    {
        isb += "intent_suggestions,";
        isb += "time_intent_suggestions_set,";
    }
    isb += "what_3_words,";
    if (!string.IsNullOrEmpty(options.NearestPlaces[i]))
    {
        isb += "nearest_place,";
        isb += "country,";
    }
    isb += "short_hash_id,";
    isb += "num_water_points_skipped,";

    updateQuery += `visited = '1',`;
    // updateQuery += `num_water_points_skipped = ${req.body.num_water_points_skipped}`; // num_water_points_skipped
    updateQuery += ` WHERE point_id='${req.body.point_id}';`;
    console.log(`UPDATE query ${updateQuery}`);
    const result = await sql.query(updateQuery);
    console.dir(result)
}

module.export = {
    saveGeneratedPoints: saveGeneratedPoints,
    saveReport: saveTripReport,
};
